const journeyCardDecks = {
    jamestown: [
        { title: "Jamestown settlement", pageTitle: "Jamestown,_Virginia", fact: "This image points to the settlement founded beside the James River in 1607, the first permanent English colony in North America." },
        { title: "Captain John Smith", pageTitle: "John_Smith_(explorer)", fact: "John Smith mapped the region and pushed settlers to work so the colony had a better chance to survive." },
        { title: "Pocahontas", pageTitle: "Pocahontas", fact: "Pocahontas became a symbol of early meetings between Powhatan communities and English settlers in Virginia." },
        { title: "Chief Powhatan", pageTitle: "Powhatan", fact: "Powhatan led a powerful confederacy of Native towns that surrounded the Jamestown colony." },
        { title: "Susan Constant", pageTitle: "Susan_Constant", fact: "The Susan Constant was the largest of the three ships that carried settlers and supplies to Virginia." },
        { title: "Godspeed ship", pageTitle: "Godspeed_(ship)", fact: "The Godspeed crossed the Atlantic in 1607 with colonists heading to the new settlement." },
        { title: "Discovery ship", pageTitle: "Discovery_(1602_ship)", fact: "The small ship Discovery explored rivers and helped move scouts and supplies around the colony." },
        { title: "Jamestown Church", pageTitle: "Jamestown_Church", fact: "The church tower at Jamestown marks one of the oldest English church sites in America." },
        { title: "John Rolfe and tobacco", pageTitle: "John_Rolfe", fact: "John Rolfe helped Jamestown grow by raising a kind of tobacco that many buyers wanted." },
        { title: "Virginia Company", pageTitle: "Virginia_Company", fact: "The Virginia Company paid for the voyage and hoped the colony would earn money through trade and crops." },
        { title: "House of Burgesses", pageTitle: "House_of_Burgesses", fact: "The House of Burgesses became one of the first elected lawmaking groups in English America." },
        { title: "James River", pageTitle: "James_River", fact: "The James River gave settlers a watery highway for travel, fishing, and trade." },
        { title: "Powhatan people", pageTitle: "Powhatan_people", fact: "Powhatan towns used local rivers, crops, and forests to support everyday life." },
        { title: "Opechancanough", pageTitle: "Opechancanough", fact: "Opechancanough became an important Powhatan leader during years of tension with colonists." },
        { title: "Starving Time", pageTitle: "Starving_Time", fact: "The winter called the Starving Time nearly wiped out Jamestown when food ran dangerously low." },
        { title: "First General Assembly", pageTitle: "First_General_Assembly_of_Virginia", fact: "This subject connects to the 1619 meeting that helped begin representative government in Virginia." },
        { title: "Colonial Virginia", pageTitle: "Colony_of_Virginia", fact: "Virginia grew from a small fort into a large colony built along rivers, farms, and ports." },
        { title: "English colonization", pageTitle: "English_colonization_of_the_Americas", fact: "English colonization brought ships, trade plans, and permanent settlements like Jamestown to the Atlantic coast." },
        { title: "Chesapeake Bay", pageTitle: "Chesapeake_Bay", fact: "The Chesapeake Bay region shaped settlement because its wide waters connected many communities." },
        { title: "Historic Jamestowne archaeology", pageTitle: "Historic_Jamestowne", fact: "Archaeologists at Historic Jamestowne keep uncovering tools, graves, and fort remains from 1607." }
    ],
    revolution: [
        { title: "Declaration of Independence", pageTitle: "Declaration_of_Independence", fact: "This image connects to the document that announced the colonies were becoming an independent nation." },
        { title: "George Washington", pageTitle: "George_Washington", fact: "George Washington led the Continental Army and later became the first U.S. president." },
        { title: "Thomas Jefferson", pageTitle: "Thomas_Jefferson", fact: "Thomas Jefferson wrote the main draft of the Declaration of Independence." },
        { title: "Benjamin Franklin", pageTitle: "Benjamin_Franklin", fact: "Benjamin Franklin used his writing and diplomacy skills to help the American cause." },
        { title: "Paul Revere", pageTitle: "Paul_Revere", fact: "Paul Revere is remembered for a warning ride that helped spread urgent news across Massachusetts." },
        { title: "Boston Tea Party", pageTitle: "Boston_Tea_Party", fact: "The Boston Tea Party became a famous protest against British taxes on tea." },
        { title: "Continental Congress", pageTitle: "Continental_Congress", fact: "Leaders from the colonies met in Congress to debate plans, write letters, and guide the revolution." },
        { title: "Lexington and Concord", pageTitle: "Battles_of_Lexington_and_Concord", fact: "The battles at Lexington and Concord are often called the first military clashes of the Revolution." },
        { title: "Valley Forge", pageTitle: "Valley_Forge", fact: "Valley Forge was the hard winter camp where Washington's army trained and stayed together." },
        { title: "Yorktown victory", pageTitle: "Siege_of_Yorktown", fact: "Yorktown became the final major victory that convinced Britain the war was ending." },
        { title: "Marquis de Lafayette", pageTitle: "Marquis_de_Lafayette", fact: "Lafayette was a young French ally who helped Washington and the Continental Army." },
        { title: "Betsy Ross", pageTitle: "Betsy_Ross", fact: "Stories about Betsy Ross connect her to an early American flag with 13 stars." },
        { title: "Gadsden flag", pageTitle: "Gadsden_flag", fact: "The coiled snake on the Gadsden flag warned others not to push the colonies around." },
        { title: "Join, or Die cartoon", pageTitle: "Join,_or_Die", fact: "Benjamin Franklin's snake cartoon urged the colonies to unite for strength." },
        { title: "Liberty Bell", pageTitle: "Liberty_Bell", fact: "The Liberty Bell became a lasting symbol of freedom and public ideals in Philadelphia." },
        { title: "Sons of Liberty", pageTitle: "Sons_of_Liberty", fact: "The Sons of Liberty organized protests and resistance against British policies." },
        { title: "Patrick Henry", pageTitle: "Patrick_Henry", fact: "Patrick Henry was a fiery speaker who urged Americans to stand up for liberty." },
        { title: "Continental Army", pageTitle: "Continental_Army", fact: "The Continental Army was made up of soldiers from many colonies fighting together." },
        { title: "Cornwallis surrender painting", pageTitle: "Surrender_of_Lord_Cornwallis", fact: "This famous scene shows the surrender that marked the end of the Revolutionary War." },
        { title: "Committee of Five", pageTitle: "Committee_of_Five", fact: "The Committee of Five helped draft and present the Declaration of Independence." }
    ],
    frontier: [
        { title: "Oregon Trail", pageTitle: "Oregon_Trail", fact: "The Oregon Trail carried wagon families west for months across plains, rivers, and mountains." },
        { title: "Lewis and Clark", pageTitle: "Lewis_and_Clark_Expedition", fact: "Lewis and Clark mapped routes, plants, animals, and rivers across the West." },
        { title: "Pony Express", pageTitle: "Pony_Express", fact: "The Pony Express sped mail west by swapping riders and horses at relay stations." },
        { title: "Homestead Act", pageTitle: "Homestead_Act", fact: "The Homestead Act offered land to families who built homes and farmed it." },
        { title: "California Gold Rush", pageTitle: "California_Gold_Rush", fact: "The Gold Rush drew thousands of people west hoping to find gold and quick wealth." },
        { title: "Conestoga wagon", pageTitle: "Conestoga_wagon", fact: "Covered wagons carried food, tools, and family supplies across long frontier routes." },
        { title: "Chimney Rock landmark", pageTitle: "Chimney_Rock_National_Historic_Site", fact: "Chimney Rock was a famous trail landmark that let travelers know they were making progress." },
        { title: "Sod house", pageTitle: "Sod_house", fact: "Settlers on the plains built sod houses from thick blocks of prairie earth when wood was scarce." },
        { title: "Chisholm Trail", pageTitle: "Chisholm_Trail", fact: "The Chisholm Trail helped cowboys drive cattle from Texas toward rail lines in Kansas." },
        { title: "Buffalo Bill", pageTitle: "Buffalo_Bill", fact: "Buffalo Bill became a frontier celebrity by turning western stories into stage shows." },
        { title: "Sitting Bull", pageTitle: "Sitting_Bull", fact: "Sitting Bull is remembered as a leader who defended Lakota land and independence." },
        { title: "Deadwood town", pageTitle: "Deadwood,_South_Dakota", fact: "Deadwood grew quickly as miners, merchants, and travelers rushed into the Black Hills." },
        { title: "Great Plains", pageTitle: "Great_Plains", fact: "The Great Plains stretched wide and flat, shaping how settlers farmed, traveled, and built." },
        { title: "Santa Fe Trail", pageTitle: "Santa_Fe_Trail", fact: "The Santa Fe Trail linked Missouri to markets in the Southwest for trade and travel." },
        { title: "Overland Trail", pageTitle: "Overland_Trail", fact: "The Overland Trail was another major westward route used by stagecoaches and wagon trains." },
        { title: "Prairie schooner", pageTitle: "Prairie_schooner", fact: "A prairie schooner was a smaller covered wagon often seen rolling across open grasslands." },
        { title: "Gold panning", pageTitle: "Gold_panning", fact: "Gold panning used a shallow pan to separate shiny flakes from river sand and gravel." },
        { title: "Texas longhorns", pageTitle: "Texas_Longhorn", fact: "Texas longhorn cattle were hardy animals that could travel long distances on dusty drives." },
        { title: "Cattle drives", pageTitle: "Cattle_drives_in_the_United_States", fact: "Large cattle drives moved herds north to railheads where beef could be shipped east." },
        { title: "Transcontinental railroad", pageTitle: "First_transcontinental_railroad", fact: "The first transcontinental railroad changed western travel by shrinking a months-long trip to days." }
    ],
    reconstruction: [
        { title: "Abraham Lincoln", pageTitle: "Abraham_Lincoln", fact: "Lincoln guided the country through the Civil War and set the stage for rebuilding afterward." },
        { title: "Emancipation Proclamation", pageTitle: "Emancipation_Proclamation", fact: "The Emancipation Proclamation changed the meaning of the war by declaring freedom for many enslaved people." },
        { title: "Freedmen's Bureau", pageTitle: "Freedmen's_Bureau", fact: "The Freedmen's Bureau helped families find food, schools, jobs, and legal support after the war." },
        { title: "Howard University", pageTitle: "Howard_University", fact: "Howard University was founded during Reconstruction and became an important place for higher learning." },
        { title: "Hampton Institute", pageTitle: "Hampton_University", fact: "Hampton Institute opened new paths in teacher training and education after the war." },
        { title: "Hiram Revels", pageTitle: "Hiram_Rhodes_Revels", fact: "Hiram Revels became the first Black American to serve in the U.S. Senate." },
        { title: "Thirteenth Amendment", pageTitle: "Thirteenth_Amendment_to_the_United_States_Constitution", fact: "The Thirteenth Amendment ended slavery in the United States." },
        { title: "Fourteenth Amendment", pageTitle: "Fourteenth_Amendment_to_the_United_States_Constitution", fact: "The Fourteenth Amendment defined citizenship and promised equal protection under the law." },
        { title: "Fifteenth Amendment", pageTitle: "Fifteenth_Amendment_to_the_United_States_Constitution", fact: "The Fifteenth Amendment protected voting rights for many newly enfranchised men." },
        { title: "Reconstruction era", pageTitle: "Reconstruction_era", fact: "Reconstruction was the period when the nation tried to rebuild laws, schools, transport, and government." },
        { title: "Clara Barton", pageTitle: "Clara_Barton", fact: "Clara Barton organized aid for wounded people and later helped start the American Red Cross." },
        { title: "American Red Cross", pageTitle: "American_Red_Cross", fact: "The American Red Cross became known for disaster relief and emergency help." },
        { title: "Brooklyn Bridge", pageTitle: "Brooklyn_Bridge", fact: "The Brooklyn Bridge showed how new engineering could reconnect growing cities after the war years." },
        { title: "National railroad link", pageTitle: "First_transcontinental_railroad", fact: "A nation tied together by rail could move people, mail, and goods much faster than before." },
        { title: "Alexander Graham Bell", pageTitle: "Alexander_Graham_Bell", fact: "Bell's work on sound and speech led to the first practical telephone." },
        { title: "Telephone", pageTitle: "Telephone", fact: "The telephone let people share voices over wires instead of waiting for letters or telegraphs." },
        { title: "Thomas Edison", pageTitle: "Thomas_Edison", fact: "Thomas Edison helped turn inventions into tools people could use at home and at work." },
        { title: "Light bulb", pageTitle: "Incandescent_light_bulb", fact: "Electric light bulbs made it easier for schools, shops, and homes to stay bright after dark." },
        { title: "John Roebling", pageTitle: "John_A._Roebling", fact: "John Roebling designed giant suspension bridges that showed what steel cables could do." },
        { title: "Tuskegee Institute", pageTitle: "Tuskegee_University", fact: "Tuskegee grew into a major school focused on learning, skills, and leadership." }
    ],
    industrial: [
        { title: "Bessemer steel", pageTitle: "Bessemer_process", fact: "The Bessemer process made it possible to turn iron into strong steel much faster and cheaper." },
        { title: "Carnegie Steel", pageTitle: "Carnegie_Steel_Company", fact: "Carnegie Steel helped supply beams, rails, and metal parts for a rapidly growing nation." },
        { title: "Thomas Edison", pageTitle: "Thomas_Edison", fact: "Edison built labs and businesses that turned inventions into everyday products." },
        { title: "Electric light", pageTitle: "Incandescent_light_bulb", fact: "Practical light bulbs helped factories and city streets stay active after sunset." },
        { title: "Alexander Graham Bell", pageTitle: "Alexander_Graham_Bell", fact: "Bell's inventions helped people send voices across towns and cities." },
        { title: "Telephone", pageTitle: "Telephone", fact: "Telephones changed business by speeding up orders, news, and conversations." },
        { title: "Singer sewing machines", pageTitle: "Singer_Corporation", fact: "Singer sewing machines helped families and clothing shops sew faster and more neatly." },
        { title: "Factory work", pageTitle: "Factory", fact: "Factories gathered workers, machines, and power into one place to make goods quickly." },
        { title: "Assembly line", pageTitle: "Assembly_line", fact: "Assembly lines sped up production by giving each worker one repeatable part of the job." },
        { title: "Model T", pageTitle: "Ford_Model_T", fact: "The Model T made cars affordable for many families and changed how Americans traveled." },
        { title: "Statue of Liberty", pageTitle: "Statue_of_Liberty", fact: "The Statue of Liberty welcomed newcomers and became a symbol of hope and arrival." },
        { title: "Skyscrapers", pageTitle: "Skyscraper", fact: "Skyscrapers rose because steel frames and elevators made much taller buildings possible." },
        { title: "Home Insurance Building", pageTitle: "Home_Insurance_Building", fact: "The Home Insurance Building is often called one of the first skyscrapers." },
        { title: "Flatiron Building", pageTitle: "Flatiron_Building", fact: "The Flatiron Building's unusual triangle shape made it one of New York's best-known towers." },
        { title: "Subway systems", pageTitle: "New_York_City_Subway", fact: "Subways helped crowded cities move huge numbers of riders below busy streets." },
        { title: "Wright brothers", pageTitle: "Wright_brothers", fact: "The Wright brothers showed how careful engineering could lift powered flight off the ground." },
        { title: "Kodak cameras", pageTitle: "Kodak", fact: "Kodak made photography easier for everyday people, not just experts." },
        { title: "Sewing machine", pageTitle: "Sewing_machine", fact: "Sewing machines changed homes and factories by making clothes faster to produce and repair." },
        { title: "Elevators", pageTitle: "Elevator", fact: "Elevators helped workers and shoppers move safely inside larger, taller buildings." },
        { title: "Textile mills", pageTitle: "Cotton_mill", fact: "Cotton mills used belts, spindles, and looms to turn raw fiber into thread and cloth." }
    ],
    railroad: [
        { title: "First transcontinental railroad", pageTitle: "First_transcontinental_railroad", fact: "This railroad linked the East and West, cutting cross-country travel from months to days." },
        { title: "Golden Spike", pageTitle: "Golden_spike", fact: "The Golden Spike ceremony celebrated the joining of major rail lines at Promontory Summit." },
        { title: "Union Pacific", pageTitle: "Union_Pacific_Railroad", fact: "Union Pacific built track westward across plains and mountains." },
        { title: "Central Pacific", pageTitle: "Central_Pacific_Railroad", fact: "Central Pacific pushed rails eastward, often through difficult mountain terrain." },
        { title: "Grand Central Terminal", pageTitle: "Grand_Central_Terminal", fact: "Grand Central became one of America's busiest and most famous railroad stations." },
        { title: "Steam locomotive", pageTitle: "Steam_locomotive", fact: "Steam locomotives used fire, water, and pressure to pull passengers and freight." },
        { title: "Pullman Company", pageTitle: "Pullman_Company", fact: "The Pullman Company built rail cars that made long train trips more comfortable." },
        { title: "George Pullman", pageTitle: "George_Pullman", fact: "George Pullman became known for designing sleeping cars for overnight train travel." },
        { title: "Caboose", pageTitle: "Caboose", fact: "A caboose rode at the back of many freight trains and gave crews a workspace on the move." },
        { title: "Telegraph lines", pageTitle: "Telegraphy", fact: "Telegraph wires often followed rail routes so dispatchers could send messages quickly." },
        { title: "Railway post office", pageTitle: "Railway_post_office", fact: "Railway post office cars sorted mail while the train was still moving." },
        { title: "Freight trains", pageTitle: "Freight_train", fact: "Freight trains carried coal, grain, lumber, and factory goods across long distances." },
        { title: "Dining cars", pageTitle: "Dining_car", fact: "Dining cars let travelers eat full meals while the train rolled across the country." },
        { title: "Sleeping cars", pageTitle: "Sleeping_car", fact: "Sleeping cars turned long rides into overnight journeys with beds and private spaces." },
        { title: "Promontory Summit", pageTitle: "Promontory_Summit", fact: "Promontory Summit in Utah became famous as the meeting point of major rail crews." },
        { title: "Pennsylvania Railroad", pageTitle: "Pennsylvania_Railroad", fact: "The Pennsylvania Railroad grew into one of the largest railroad companies in the world." },
        { title: "Track switches", pageTitle: "Track_switch", fact: "Track switches guide trains from one rail line to another with careful timing and control." },
        { title: "Passenger trains", pageTitle: "Passenger_train", fact: "Passenger trains carried families, business travelers, and tourists between distant cities." },
        { title: "Railroad conductors", pageTitle: "Conductors_(transportation)", fact: "Conductors checked tickets, helped riders, and kept the trip running on schedule." },
        { title: "Rail transport network", pageTitle: "Rail_transport_in_the_United_States", fact: "America's rail network connected farms, mines, towns, ports, and cities into one system." }
    ],
    modern: [
        { title: "Hoover Dam", pageTitle: "Hoover_Dam", fact: "Hoover Dam showed how modern engineering could control water and generate huge amounts of power." },
        { title: "Grand Coulee Dam", pageTitle: "Grand_Coulee_Dam", fact: "Grand Coulee Dam helped provide electricity and irrigation across the Pacific Northwest." },
        { title: "Empire State Building", pageTitle: "Empire_State_Building", fact: "The Empire State Building became an icon of fast city construction and modern skylines." },
        { title: "Golden Gate Bridge", pageTitle: "Golden_Gate_Bridge", fact: "The Golden Gate Bridge connected San Francisco to nearby counties with a dramatic span." },
        { title: "Interstate highways", pageTitle: "Interstate_Highway_System", fact: "Interstate highways changed travel by linking states with fast roads for cars and trucks." },
        { title: "Levittown suburb", pageTitle: "Levittown,_Pennsylvania", fact: "Levittown became a symbol of postwar suburb growth with rows of new family homes." },
        { title: "Shopping malls", pageTitle: "Shopping_mall", fact: "Shopping malls gathered many stores into one climate-controlled place for families to visit." },
        { title: "Suburban neighborhoods", pageTitle: "Suburb", fact: "Suburbs grew as more families moved outside city centers into planned neighborhoods." },
        { title: "Drive-in theaters", pageTitle: "Drive-in_theater", fact: "Drive-in theaters let families watch movies from inside their cars." },
        { title: "Television at home", pageTitle: "Television", fact: "Television became a shared family screen for news, sports, and entertainment." },
        { title: "American diners", pageTitle: "Diner", fact: "Diners became familiar roadside restaurants for travelers and local communities." },
        { title: "Martin Luther King Jr.", pageTitle: "Martin_Luther_King_Jr.", fact: "Dr. King became one of the best-known voices of the civil rights movement." },
        { title: "March on Washington", pageTitle: "March_on_Washington_for_Jobs_and_Freedom", fact: "The March on Washington brought huge crowds together to demand civil rights and opportunity." },
        { title: "Civil rights movement", pageTitle: "Civil_rights_movement", fact: "The civil rights movement challenged unfair laws and pushed the country toward greater equality." },
        { title: "School desegregation", pageTitle: "School_desegregation_in_the_United_States", fact: "School desegregation changed classrooms by challenging laws that had kept children apart." },
        { title: "Vietnam War protests", pageTitle: "Vietnam_War_protests", fact: "Large protests showed how citizens used marches and signs to speak about war and peace." },
        { title: "Woodstock", pageTitle: "Woodstock", fact: "Woodstock became a symbol of music, youth culture, and big outdoor gatherings." },
        { title: "Color television", pageTitle: "Color_television", fact: "Color television changed how families watched sports, cartoons, and news at home." },
        { title: "Air conditioning", pageTitle: "Air_conditioning", fact: "Air conditioning changed work, travel, and daily life by cooling homes, schools, and stores." },
        { title: "Supermarkets", pageTitle: "Supermarket", fact: "Supermarkets gathered many foods in one place and changed how families shopped each week." }
    ],
    "space-race": [
        { title: "Apollo 11", pageTitle: "Apollo_11", fact: "Apollo 11 carried the first humans to walk on the Moon in 1969." },
        { title: "Buzz Aldrin", pageTitle: "Buzz_Aldrin", fact: "Buzz Aldrin became one of the first two people to walk on the lunar surface." },
        { title: "Saturn V rocket", pageTitle: "Saturn_V", fact: "The Saturn V rocket was powerful enough to lift Apollo spacecraft toward the Moon." },
        { title: "Yuri Gagarin", pageTitle: "Yuri_Gagarin", fact: "Yuri Gagarin became the first human to travel into space in 1961." },
        { title: "John Glenn", pageTitle: "John_Glenn", fact: "John Glenn became the first American to orbit Earth." },
        { title: "Gemini 4 spacewalk", pageTitle: "Gemini_4", fact: "Gemini 4 is remembered for the first American spacewalk." },
        { title: "Skylab", pageTitle: "Skylab", fact: "Skylab was America's first space station and a home for astronauts in orbit." },
        { title: "Alan Shepard", pageTitle: "Alan_Shepard", fact: "Alan Shepard became the first American in space and later walked on the Moon." },
        { title: "Neil Armstrong", pageTitle: "Neil_Armstrong", fact: "Neil Armstrong became the first person to step onto the Moon." },
        { title: "Apollo 17", pageTitle: "Apollo_17", fact: "Apollo 17 was the last mission to land astronauts on the Moon." },
        { title: "Valentina Tereshkova", pageTitle: "Valentina_Tereshkova", fact: "Valentina Tereshkova became the first woman to travel into space." },
        { title: "Apollo 8", pageTitle: "Apollo_8", fact: "Apollo 8 was the first crewed mission to orbit the Moon." },
        { title: "Earthrise", pageTitle: "Earthrise", fact: "The Earthrise photo gave people a new view of our planet hanging above the Moon." },
        { title: "Mission Control", pageTitle: "Christopher_C._Kraft_Jr._Mission_Control_Center", fact: "Mission Control tracked spacecraft systems and guided astronauts from Earth." },
        { title: "Viking 1", pageTitle: "Viking_1", fact: "Viking 1 sent back the first successful images from the surface of Mars." },
        { title: "Mariner probes", pageTitle: "Mariner_program", fact: "Mariner spacecraft flew past nearby planets and sent home new pictures and data." },
        { title: "Telstar satellite", pageTitle: "Telstar", fact: "Telstar helped relay television signals and showed how satellites could connect the world." },
        { title: "Space Shuttle Columbia", pageTitle: "Space_Shuttle_Columbia", fact: "Columbia launched the shuttle era, when spacecraft could be used again and again." },
        { title: "Neutral buoyancy training", pageTitle: "Neutral_buoyancy", fact: "Astronauts trained underwater to practice space tasks that feel almost weightless." },
        { title: "Lunar module", pageTitle: "Apollo_Lunar_Module", fact: "The lunar module was the spacecraft built to land astronauts on the Moon and lift them back to orbit." }
    ]
};

window.journeyCardDecks = journeyCardDecks;